### ISSUE TITLE
Are variants persisted in cookie copied to redis on login ?

### ISSUE THREAD

**Issue by avifoxi** [splitrb/split#483] opened 2017-04-10 20:27 UTC
My Rails app has 2 experiments configured:
1) Price
2) Payment provider

Only users in `Price:control` may can see variants for Payment.

Users see a Price variant before they authenticate. 
Then they log in.
Then they see Payment variants. 

After login, I seem to lose the variant data that was stored in a cookie, and it is not persisted to Redis. This is a problem, because I am explicitly verifying inclusion in the Payment group before exposing Provider variants. 

I am getting around this by persisting Split variants to a Rails session, which is persistent before and after login. 

I would expect that Split variant data for a user would also persist through a user session.
Is this known behavior? 

If I can provide any more information to clarify the issue, please ask. 

-- 
I am running Rails 4.2.7.1, and Split 1.6.0
I thought a Split update might resolve the issue, but upgrading to 3.0.0 (testing locally) does not seem to resolve the issue.

**Comment by peeinears** [comment] 2017-08-09 20:53
I also had this misconception about the `DualAdapter`. From looking at the code, it doesn't look like the `DualAdapter` supports transferring data between the logged out adapter and the logged in adapter. This feature would be awesome to have, but for now it's probably most helpful to just add a line to the README to prevent any future confusion (I can try to do this if I have time.)

@avifoxi I was able to manually transfer A/B data from my logged out adapter (CookieAdapter) to my logged in adapter (RedisAdapter) by initializing adapters and getting/setting values directly.

For instance, you could do something like this...
```ruby
logged_out_adapter = Split::Persistence::CookieAdapter(self)
logged_in_adapter = Split::Persistence::RedisAdapter.new(self, current_user.id)
logged_out_adapter.keys.each do |experiment|
  logged_in_adapter[experiment] ||= logged_out_adapter[experiment]
end
```

**A warning though:** I suspect that Split's reporting might then count users who have data in both logged in and logged out adapters as 2 distinct A/B test users.

**Comment by nitsujri** [comment] 2018-06-28 00:56
@peeinears Thanks for this, I was running into the same issue.

Where do you stick this code?

Not sure what the `self` context is referring to.

**Comment by peeinears** [comment] 2018-06-28 01:52
@nitsujri FYI, I ended up going with a different solution (one that covered only the specific test that I wanted to transfer) so I can't really report much about my experience with that code snippet. IIRC, it was intended to go in any controller actions that logged a user in (e.g. login and signup).

**Comment by nitsujri** [comment] 2018-06-28 01:56
@peeinears makes sense. I think the key is the concept that you delivered and you deserve the credit to put it into the docs!

**Comment by santib** [comment] 2019-10-04 19:57
I was thinking that maybe a behavior where it first looks in Redis and if it's not there it looks in the cookies could make more sense that the `DualAdapter` behavior. Would the following adapter solve this issue?
```
module Split
  module Persistence
    class CustomDualAdapter
      def initialize(context)
        if logged_in = self.class.config[:logged_in]
        else
          raise "Please configure :logged_in"
        end
        if logged_in_adapter = self.class.config[:logged_in_adapter]
        else
          raise "Please configure :logged_in_adapter"
        end
        if logged_out_adapter = self.class.config[:logged_out_adapter]
        else
          raise "Please configure :logged_out_adapter"
        end

        @logged_in = logged_in.call(context)
        @logged_in_adapter = logged_in_adapter.new(context)
        @logged_out_adapter = logged_out_adapter.new(context)
      end

      def self.with_config(options={})
        self.config.merge!(options)
        self
      end

      def self.config
        @config ||= {}
      end

      def keys
        (@logged_in_adapter.keys + @logged_out_adapter.keys).uniq
      end

      def [](key)
        @logged_in_adapter[key] || @logged_out_adapter[key]
      end

      def []=(key, value)
        if @logged_in
          @logged_in_adapter[key] = value
        else
          @logged_out_adapter[key] = value
        end
      end

      def delete(key)
        @logged_in_adapter.delete(key)
        @logged_out_adapter.delete(key)
      end
    end
  end
end
```

**Comment by andrehjr** [comment] 2020-07-05 01:58
On #588 we added the possibility of recovering the alternative selected via the Dual Adapter. It's not the default behavior yet but can set `fallback_to_logged_out_adapter = true` when setting up split.

**Closed by andrehjr** 2020-07-05 01:58 UTC
