### ISSUE TITLE
JS and CSS files couldn't be found in staging and production mode.

### ISSUE THREAD

**Issue by alpaca0984** [splitrb/split#386] opened 2016-05-05 01:32 UTC
similar issue with https://github.com/splitrb/split/issues/210

When i deployed code on production server, 
reset.css / split.css / dashboard.js files couldn't be found(return 404 error).

files path in HEAD tag are /split/dashboard.js, /split/reset.css, /split/split.css but
capistrano deployment doesn't create /public/split directory.

My environment => Rails: 4.2.1, Ruby: 2.1.5, split: 1.4.2, sinatra: 1.4.7

Any help would be appreciated.

**Comment by ccallebs** [comment] 2016-05-09 21:45
@alpaca0984 This occasionally happens to me as well. I don't know the root cause, but it eventually corrects itself. In the meantime opening it up in another browser should do the trick.

**Comment by hiemanshu** [comment] 2016-07-07 15:01
I'm facing the same issue as well. It works well locally, but doesn't work on Staging/Production.

**Comment by hiemanshu** [comment] 2016-07-11 17:35
I eventually fixed this issue by sym-linking the `public` dashboard folder to my `public/<mountpoint>` folder in Capistrano.

**Comment by andrew** [comment] 2017-03-30 18:08
Closing as this issue it's nearly a year old, please reopen if it's still affecting you.

**Closed by andrew** 2017-03-30 18:08 UTC
