### ISSUE TITLE
How can I call ab_finished in $("#test_btn").on("click", function() {}) ?

### ISSUE THREAD

**Issue by ying13** [splitrb/split#653] opened 2021-01-28 04:58 UTC
There is a button in our website which links to another website and we want set the conversion to be button click. How to we use ab_finished?

**Comment by andrehjr** [comment] 2021-01-28 18:52
You need to make a request to a controller where you can call `ab_finished`.

I think you can either make an ajax request or just make click go through your controller and call redirect_to there.

Closing as this is not a bug.

**Closed by andrehjr** 2021-01-28 18:52 UTC
